file_format: "1.0"

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: basic

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
